paths:
  /instrumentos:
    get:
      summary: Retorna a lista de todos os instrumentos cadastrados
      tags: [Instrumentos]
      security:
        - bearerAuth: [] 
      responses:
        200:
          description: Lista de instrumentos
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  properties:
                    _id:
                      type: string
                      example: "6782b9b16d6ea34ace5bd19968c97269117f2dbe4d66b5a2"
                    name:
                      type: string
                      example: "Guitarra Elétrica"
                    category:
                      type: string
                      example: "Cordas"
                    description:
                      type: string
                      example: "Instrumento elétrico versátil para vários estilos musicais"  
                    price:
                      type: integer
                      example: 3400
        500:
          description: Erro interno do servidor

    post:
      summary: Cria um novo instrumento
      tags: [Instrumentos]
      security:
        - bearerAuth: []
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - name
                - category
                - description
                - price
              properties:
                name:
                  type: string
                  example: "Guitarra Elétrica"
                category:
                  type: string
                  example: "Cordas"
                description:
                  type: string
                  example: "Instrumento elétrico versátil para vários estilos musicais"
                price:
                  type: integer
                  example: 3400
      responses:
        201:
          description: Instrumento criado com sucesso
        500:
          description: Erro interno do servidor

  /instrumentos/{id}:
    get:
      summary: Retorna um instrumento pelo ID
      tags: [Instrumentos]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        200:
          description: Instrumento encontrado
          content:
            application/json:
              schema:
                type: object
                properties:
                  instrumento:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "6782b9b16d6ea34ace5bd19968c97269117f2dbe4d66b5a2"
                      name:
                        type: string
                        example: "Guitarra Elétrica"
                      category:
                        type: string
                        example: "Cordas"
                      description:
                        type: string
                        example: "Instrumento elétrico versátil para vários estilos musicais"
                      price:
                        type: integer
                        example: 3400
        404:
          description: Instrumento não encontrado
        500:
          description: Erro interno do servidor

    put:
      summary: Atualiza um instrumento existente
      tags: [Instrumentos]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                name:
                  type: string
                  example: "Guitarra Elétrica"
                category:
                  type: string
                  example: "Cordas"
                description:
                  type: string
                  example: "Instrumento elétrico versátil para vários estilos musicais"
                price:
                  type: integer
                  example: 3400
      responses:
        200:
          description: Instrumento atualizado com sucesso
          content:
            application/json:
              schema:
                type: object
                properties:
                  instrumento:
                    type: object
                    properties:
                      _id:
                        type: string
                        example: "6782b9b16d6ea34ace5bd19968c97269117f2dbe4d66b5a2"
                      name:
                        type: string
                        example: "Guitarra Elétrica"
                      category:
                        type: string
                        example: "Cordas"
                      description:
                        type: string
                        example: "Instrumento elétrico versátil para vários estilos musicais"
                      price:
                        type: integer
                        example: 3400
        500:
          description: Erro interno do servidor

    delete:
      summary: Remove um instrumento pelo ID
      tags: [Instrumentos]
      security:
        - bearerAuth: []
      parameters:
        - name: id
          in: path
          required: true
          schema:
            type: string
      responses:
        204:
          description: Instrumento deletado com sucesso
        400:
          description: ID inválido
        500:
          description: Erro interno do servidor
